---
title: "map_interactive"
author: "Derek Rice"
date: "2024-06-22"
output: html_document
---

cite: https://www.youtube.com/watch?v=efj6-aawubs

```{r}
if (!require("pacman"))
  install.packages("pacman")

pacman::p_load(tidyverse,
               giscoR,
               janitor,
               s2,
               ggiraph)

germany_districts <- gisco_get_nuts(
  country = 'Germany',
  nuts_level = 3,
  year = "2021",
  epsg = 3035) |>
    as_tibble() |>
    clean_names() 

germany_states <- gisco_get_nuts(
  country = 'Germany',
  nuts_level = 1,
  year = "2021",
  epsg = 3035) |>
    as_tibble() |>
    clean_names() 
```


```{r}
gg_plt <- germany_districts |>
  ggplot(aes (geometry = geometry)) +
  geom_sf(data = germany_states, 
          aes(fill = nuts_name),
          color = "blue",
          linewidth = 1) +
  geom_sf_interactive(
    fill = NA,
    aes(
      data_id = nuts_id,
      tooltip = nuts_name
    ),
    color = "red",
    linewidth = 0.1
  )

girafe(ggobj = gg_plt)

```

```{r}


```