---
title: "review_interactive_maps"
author: "Derek Rice"
date: "2024-06-23"
output: html_document
---

```{r setup, include = FALSE}
#| label: load-pkgs
#| message: false

knitr::opts_chunk$set(echo = TRUE)

if (!require("pacman"))
    install.packages("pacman")

pacman::p_load(tmap,
               spData,
               plotly,
               dplyr,
               readr,
               tidyverse
               )

# cite: https://www.youtube.com/watch?v=VnbnaPeI6pY

data(world)

tmap_mode("plot") #view = interactive

tm_shape(world) +tm_polygons('pop')

# view(world)


tm_shape(world) +tm_polygons(c('pop','area_km2')) + tm_facets(sync = TRUE, ncol = 2)



```

```{r}
# cite: https://www.youtube.com/watch?v=RrtqBYLf404

minwage_df <- read_csv("data/Minimum Wage Data.csv") 
states <- read_csv("data/states.csv")

#view(states)
#view(minwage_df)

wage_columns <- grep("wage", names(minwage_df), ignore.case = TRUE, value = TRUE)
wage_columns

minwage <- minwage_df |>
  inner_join(states, by = c("State" = "state")) |>
  mutate(highest_wage = apply(across(all_of(wage_columns)), 1,min, na.rm = TRUE)) |>
  select(Year, State, code, highest_wage)

# view(minwage)

```

```{r}

minwage_graph <- plot_geo(minwage,
                          locationmode = "USA-states",
                          frame = ~Year) |>
  add_trace(locations = ~code,
            z = ~highest_wage)


minwage_graph

```


```{r}

minwage_graph <- plot_geo(minwage,
                          locationmode = "USA-states",
                          frame = ~Year) |>
  add_trace(locations = ~code,
            z = ~highest_wage,
            zmin = 0,
            zmax = max(minwage$highest_wage),
            colour = ~highest_wage) |>
  layout(geo = list(scope = 'usa'))


minwage_graph

```

```{r}

minwage <- minwage |>
  mutate(hover = paste0(State, "\n$", highest_wage))


fontStyle = list(
  family = "DM Sans",
  size = 15,
  colour = "black")

label = list(
  bgcolour = "#EEEEEE",
  bordercolour = "transparent",
  font = fontStyle
)

# view(minwage) # need tidyverse 

minwage_graph <- plot_geo(minwage,
                          locationmode = "USA-states",
                          frame = ~Year) |>
  add_trace(locations = ~code,
            z = ~highest_wage,
            zmin = 0,
            zmax = round(max(minwage$highest_wage),2),
            colour = ~highest_wage,
            text = ~ hover,
            hoverinfo = "text") |>
  layout(geo = list(scope = 'usa'),
         font = list(family = "DM Sans"),
         title = "Min Wage in US\n1968 to 2020",
         legend = list(title = list(text = "wage ($)"))) |>
  style(hoverlabel = label) |>
  config(displayModeBar = FALSE) |>
  colorbar(tickprefix = "$")


minwage_graph


```

```{r}

ufos <- read_csv("data/scrubbed.csv") |>
  select(longitude, latitude, datetime, shape)

# view(ufos)

geo_properties = list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showland = TRUE,
  showsubunits = FALSE,
  landcolor = toRGB('gray10'),
  showlakes = TRUE,
  lakecolor = toRGB('white'))
                      

ufos_graph = plot_geo(ufos,
                  lat = ~ latitude,
                  lon = ~ longitude,
                  marker = list(size = 2, color = "#FFFFCC", opacity = 0.25 )) |>
  add_markers(hoverinfo = 'none') |>
  config(displayModeBar = FALSE) |>
  layout(geo = geo_properties)


ufos_graph
```


```{r}



```
